# Generated by Django 3.2.9 on 2021-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='pinterest_posters')),
                ('episode', models.IntegerField()),
                ('season', models.IntegerField()),
                ('casts', models.ManyToManyField(blank=True, null=True, to='pinterest.Cast')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='pinterest.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='pinterest_posters')),
                ('casts', models.ManyToManyField(blank=True, null=True, to='pinterest.Cast')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='pinterest.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
