# Generated by Django 3.2.9 on 2021-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='casts',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='casts',
            new_name='cast',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='pinterest_posters'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='pinterest_posters'),
        ),
    ]
